linters:
  CapitalizationInSelector:
    enabled: false
  PropertySortOrder:
    enabled: false
  LeadingZero:
    enabled: false
  BorderZero:
    enabled: false
  SelectorDepth:
    enabled: true
    max_depth: 4
