language: ruby

rvm:
  - 2.3.0
  - 2.1

sudo: false

gemfile:
  - gemfiles/Gemfile.rails-4.2
  - gemfiles/Gemfile.rails-5.0

script:
  - 'echo "Checking code style" && bundle exec phare'
  - 'echo "Running specs" && bundle exec rspec spec'

matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.rails-5.0
